python svr_asset_selection.py --exp_name SVR_Data2/1 --test_size 0.01
python svr_asset_selection.py --exp_name SVR_Data2/2 --test_size 0.02
python svr_asset_selection.py --exp_name SVR_Data2/3 --test_size 0.03   
python svr_asset_selection.py --exp_name SVR_Data2/4 --test_size 0.04
python svr_asset_selection.py --exp_name SVR_Data2/5 --test_size 0.05
python svr_asset_selection.py --exp_name SVR_Data2/6 --test_size 0.06
python svr_asset_selection.py --exp_name SVR_Data2/7 --test_size 0.07
python svr_asset_selection.py --exp_name SVR_Data2/8 --test_size 0.08
python svr_asset_selection.py --exp_name SVR_Data2/9 --test_size 0.09
python svr_asset_selection.py --exp_name SVR_Data2/10 --test_size 0.1